name: Get Citation Data

on: 
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:      

permissions:
  contents: write        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Crawler
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}

    - name: Deploy to google-scholar-stats branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./google_scholar_crawler/results
        destination_dir: .
        publish_branch: google-scholar-stats
        keep_files: false
